version: "3"

services:
  magic:
    image: martel/kurento-magic-mirror-docker
    ports:
      - 8443:8443
    links:
      - kurento
    deploy:
      mode: global

  kurento:
    image: kurento/kurento-media-server
    ports:
      - 8888:8888
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
